# Generated by Django 3.2.3 on 2021-05-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='my_app.client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='invoice_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_id',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
